#!/bin/sh
# dimit: backlight presets

NAME=`basename $0`
echo $NAME

if [ $NAME = "xdim" ]; then
    xbacklight -set 10
elif [ $NAME = "xbright" ]; then
    xbacklight -set 100
elif [ $NAME = "xzzz" ]; then
    xbacklight -set 1
else
    echo "usage: call as xdim, xbright, or xzzz"
fi

