#!/usr/bin/env python
# easy keysies -- load all the ssh private keys into yr agent

from __future__ import print_function
import os
import platform

LIFETIME = 43200

HOME = os.path.expanduser('~') + "/"
HOSTNAME = platform.node().split('.')[0]
SSH_CONFIG_DIR = HOME + ".ssh/"
EXCL_FILES = [
    'config', 'authorized_keys', 'known_hosts',
    'environment-{0}'.format(HOSTNAME),
    ]
EXCL_SUFFIX = ('.pub')

KEYFILES = [SSH_CONFIG_DIR + y for y in
            [x for x in os.listdir(SSH_CONFIG_DIR) if x not in EXCL_FILES]
            if not os.path.basename(y).endswith(EXCL_SUFFIX)]

print("Loading: {0}".format(', '.join(KEYFILES)))

# TODO: skip already added

for kf in KEYFILES:
    os.system("ssh-add -t {1} {0}".format(kf, LIFETIME))
