#!/bin/bash
# mirror - say cheese
# TODO: this is totally busted on mac

mirror_mplayer() {
    mplayer -ao none -vf mirror -vf screenshot -vo gl -tv driver=v4l2:width=1366:height=768 -fs tv://
}

mirror_mpv() {
    mpv --no-audio -vf mirror -vo opengl --tv-width 1366 --tv-height 768 -fs tv://
}

cmd_exists() {
    if `command -v $1 2>&1 /dev/null`; then
        return 0
    else
        return 1
    fi
}

if cmd_exists 'mpv'; then
    mirror_mpv
elif cmd_exists 'mplayer'; then
    mirror_mplayer
else
    echo "no supported mirror app!"; exit 1
fi
