#!/bin/bash
# mirror - say cheese
command -v mplayer >/dev/null 2>&1 || { echo >&2 "can't find mplayer.."; exit 1; }

mplayer -ao none -vf mirror -vf screenshot -vo gl -tv driver=v4l2:width=1366:height=768 -fs tv://
