#!/usr/bin/env bash
# do a git pull on every repo in $GIT_REPOS. this is set externally

pushdq() {
    command pushd "$@" > /dev/null
}

popdq() {
    command popd "$@" > /dev/null
}

if [ ! -z "$GIT_REPOS" ]; then
    for rpath in $GIT_REPOS; do
        if [[ -d "$rpath/.git" ]]; then
            echo -n "$rpath: "
            pushdq "$rpath" || continue
            git pull
            popdq
        fi
    done
else
    echo 'Please set $GIT_REPOS to a space-delimited set of paths'
fi
